// Deterministic reasoning attributes derived from tagged categories.
// Warmth and layer role are looked up, never free-generated by a model:
// consistency across the corpus is what keeps the outfit rules sound.

export type LayerRole = 'base' | 'mid' | 'outer' | 'bottom' | 'footwear' | 'accessory' | 'one-piece';

export const ITEM_STATES = ['clean', 'in-wash', 'packed', 'lent-out', 'retired'] as const;
export type ItemState = (typeof ITEM_STATES)[number];

export const EVENT_TYPES = ['work', 'casual', 'evening', 'occasion', 'athletic'] as const;
export type EventType = (typeof EVENT_TYPES)[number];

// Formality 1–5 target per event type; outfits should sit within ±1.
export const EVENT_FORMALITY: Record<EventType, number> = {
  athletic: 1,
  casual: 2,
  evening: 3,
  work: 4,
  occasion: 5,
};

const FORMALITY_SCORES: Record<string, number> = {
  athletic: 1,
  casual: 2,
  'smart-casual': 3,
  business: 4,
  formal: 5,
};

export function formalityScoreFor(formality: string | null | undefined): number | null {
  if (!formality) return null;
  return FORMALITY_SCORES[formality.toLowerCase()] ?? null;
}

// Dress code, the finer ladder the wearability pass reads: where the garment
// formality tag stops at five steps, this says "business-casual" and
// "cocktail". Scores sit on the same 1–5 line so the two can be compared.
export const DRESS_CODES = ['athleisure', 'casual', 'smart-casual', 'business-casual', 'business', 'cocktail', 'formal'] as const;
export type DressCode = (typeof DRESS_CODES)[number];

const DRESS_CODE_SCORES: Record<DressCode, number> = {
  athleisure: 1,
  casual: 2,
  'smart-casual': 3,
  'business-casual': 3.5,
  business: 4,
  cocktail: 4.5,
  formal: 5,
};

export function dressCodeScore(dressCode: string | null | undefined): number | null {
  if (!dressCode) return null;
  return DRESS_CODE_SCORES[dressCode.toLowerCase() as DressCode] ?? null;
}

/** The finer of the two when both are known: the dress code, else the formality score. */
export function effectiveFormality(item: { formalityScore?: number | null; dressCode?: string | null }): number | null {
  return dressCodeScore(item.dressCode) ?? item.formalityScore ?? null;
}

// --- Pattern scale ----------------------------------------------------------
export const PATTERN_SCALES = ['none', 'fine', 'medium', 'bold'] as const;
export type PatternScale = (typeof PATTERN_SCALES)[number];

// --- Shoe type ----------------------------------------------------------------
export const SHOE_TYPES = ['sneaker', 'trainer', 'sandal', 'flip-flop', 'loafer', 'boot', 'oxford', 'derby', 'heel', 'pump', 'mule', 'other'] as const;
export type ShoeType = (typeof SHOE_TYPES)[number];

// Subtype keywords that override the category default for layer role. The
// keyword wins over the category: a blazer tagged "top" is still a layer, and
// a jumpsuit tagged "bottom" is still a one-piece.
const MID_LAYER_KEYWORDS = ['sweater', 'jumper', 'cardigan', 'hoodie', 'sweatshirt', 'pullover', 'fleece', 'vest', 'gilet', 'blazer', 'waistcoat', 'overshirt', 'shacket'];
// Mid layers that never read as outerwear, checked before the outer list
// ("waistcoat" contains "coat").
const MID_FIRST = /waistcoat|overshirt|shacket|blazer|cardigan/;
const OUTER_KEYWORDS = ['parka', 'puffer', 'overcoat', 'peacoat', 'raincoat', 'trench', 'anorak', 'windbreaker', 'bomber', 'jacket', 'coat'];
const ONE_PIECE_KEYWORDS = ['jumpsuit', 'romper', 'playsuit', 'overall', 'dungaree', 'kaftan', 'gown', 'dress'];
// "dress shirt", "dress trousers", "dress shoes": the word is an adjective there.
const DRESS_AS_ADJECTIVE = /dress[- ]?(shirt|pant|trouser|shoe|sock|boot)/;
// Layers that can stand alone as the top of an outfit (a sweater over jeans);
// a blazer, waistcoat or overshirt wants a base top under it.
const STANDALONE_MID = /sweater|jumper|hoodie|sweatshirt|pullover|fleece|turtleneck|roll[- ]?neck|knit|cardigan/;

export function deriveLayerRole(category: string, subtype?: string | null): LayerRole | null {
  const sub = (subtype ?? '').toLowerCase();
  if (category === 'footwear') return 'footwear';
  if (category === 'accessory') return 'accessory';
  if (category === 'other') return null;
  if (sub && !DRESS_AS_ADJECTIVE.test(sub) && ONE_PIECE_KEYWORDS.some((k) => sub.includes(k))) return 'one-piece';
  // "vest top" is a tank in British English; a plain "vest" is a layer.
  if (sub && !/vest top|tank/.test(sub)) {
    if (MID_FIRST.test(sub)) return 'mid';
    if (OUTER_KEYWORDS.some((k) => sub.includes(k))) return 'outer';
    if (MID_LAYER_KEYWORDS.some((k) => sub.includes(k))) return 'mid';
  }
  switch (category) {
    case 'top':
      return 'base';
    case 'outerwear':
      return 'outer';
    case 'bottom':
      return 'bottom';
    case 'dress':
      return 'one-piece';
    default:
      return null;
  }
}

/** Kept for existing callers; same table as deriveLayerRole. */
export function layerRoleFor(category: string, subtype?: string | null): LayerRole | null {
  return deriveLayerRole(category, subtype);
}

/** A mid layer that reads as a top on its own (knitwear), not one that needs a shirt under it. */
export function midStandsAlone(subtype?: string | null): boolean {
  return STANDALONE_MID.test((subtype ?? '').toLowerCase());
}

/** A base that layers under a one-piece: a fine knit, a turtleneck, a bodysuit. */
export function layersUnderOnePiece(subtype?: string | null, texture?: string | null): boolean {
  const sub = (subtype ?? '').toLowerCase();
  return /turtleneck|roll[- ]?neck|polo[- ]?neck|bodysuit|knit|thermal|long[- ]sleeve/.test(sub) || (texture ?? '').toLowerCase() === 'knit';
}

function detail(details: unknown, key: string): string {
  if (!details || typeof details !== 'object') return '';
  const v = (details as Record<string, unknown>)[key];
  return typeof v === 'string' ? v.toLowerCase() : '';
}

// Tops that don't finish an outfit on their own in a dressed setting: they
// want a layer over them.
const NEEDS_LAYER_KEYWORDS = /camisole|\bcami\b|tank|vest top|\bslip\b|bralette|bandeau|tube top|strapless|halter/;
const SHEER = /sheer|mesh|lace|see[- ]through|organza|chiffon|fishnet/;

export function deriveNeedsLayer(
  subtype?: string | null,
  details?: unknown,
  material?: string | null,
  formalityScore?: number | null,
): boolean {
  const sub = (subtype ?? '').toLowerCase();
  const mat = (material ?? '').toLowerCase();
  const note = detail(details, 'materialNote');
  if (NEEDS_LAYER_KEYWORDS.test(sub)) return true;
  if (SHEER.test(sub) || SHEER.test(mat) || SHEER.test(note)) return true;
  const sleeve = detail(details, 'sleeve');
  const sleeveless = /sleeveless|strapless|none|spaghetti|thin strap/.test(sleeve);
  if (/crop/.test(sub) && sleeveless && (formalityScore ?? 0) >= 4) return true;
  return false;
}

// Footwear formality ladder, 1–5. The garment-level formality tag is too
// coarse for shoes: "smart-casual sneakers" still sit two steps under
// trousers cut for the office. Compound keywords first, then singles.
const SHOE_FORMALITY: [RegExp, number][] = [
  [/flip[- ]?flop|slider|\bslide|thong sandal|pool sandal|croc/, 1],
  [/running|gym shoe|training shoe|trainer shoe|athletic|cleat|football boot|hiking|hiker|trail/, 1],
  [/combat|work boot|snow boot|wellington|welly|rain boot|duck boot|moon boot/, 2],
  [/heeled sandal|heel sandal|strappy sandal|evening sandal/, 3],
  [/sneaker|trainer|canvas|plimsoll|skate|tennis shoe|high[- ]?top|slip-on sneaker/, 2],
  [/sandal|espadrille|clog|boat shoe|deck shoe|birkenstock/, 2],
  [/chelsea|ankle boot|chukka|desert boot|heeled boot|knee[- ]?high|riding boot/, 3],
  [/boot/, 3],
  [/loafer|mule|moccasin|driving shoe|ballet|flat|mary jane|wedge/, 3],
  [/derby|brogue|monk|dress shoe|slingback|kitten heel|block heel|d'orsay/, 4],
  [/stiletto|high heel|platform heel|court shoe/, 5],
  [/oxford|pump|heel/, 4],
];

/** 1–5 for a recognised footwear subtype; null when the subtype says nothing. */
export function deriveShoeFormality(subtype?: string | null): number | null {
  const sub = (subtype ?? '').toLowerCase();
  if (!sub) return null;
  const hit = SHOE_FORMALITY.find(([re]) => re.test(sub));
  return hit ? hit[1] : null;
}

/**
 * Shoe formality: the subtype on the ladder first, then the catalogued shoe
 * type (sneaker, loafer, oxford …) when the subtype says nothing, then the
 * garment formality.
 */
export function shoeFormalityOf(subtype: string | null | undefined, formalityScore: number | null | undefined, shoeType?: string | null): number | null {
  return deriveShoeFormality(subtype) ?? (shoeType && shoeType !== 'other' ? deriveShoeFormality(shoeType) : null) ?? formalityScore ?? null;
}

const OPEN_TOE = /sandal|flip[- ]?flop|slider|\bslide|thong|peep[- ]?toe|open[- ]?toe|espadrille|birkenstock|croc/;

export function isOpenToe(subtype?: string | null, details?: unknown): boolean {
  const sub = (subtype ?? '').toLowerCase();
  if (OPEN_TOE.test(sub)) return true;
  const toe = detail(details, 'toe');
  return /open|peep/.test(toe);
}

const WEATHERPROOF = /wellington|welly|rain boot|duck boot|snow boot|gore-?tex|waterproof|hiking|hiker|work boot|combat|chelsea/;
const WEATHERPROOF_MATERIAL = /rubber|leather|gore|waxed|nylon|synthetic/;

export function isWeatherproof(subtype?: string | null, material?: string | null): boolean {
  const sub = (subtype ?? '').toLowerCase();
  const mat = (material ?? '').toLowerCase();
  if (WEATHERPROOF.test(sub)) return true;
  if (isOpenToe(sub)) return false;
  return /boot/.test(sub) && WEATHERPROOF_MATERIAL.test(mat);
}

/** A closed boot with real warmth — the wrong thing on a hot day. */
export function isHeavyBoot(subtype?: string | null, warmthValue?: number | null): boolean {
  const sub = (subtype ?? '').toLowerCase();
  if (!/boot/.test(sub) || /ankle boot|chelsea|desert|chukka/.test(sub)) return false;
  return (warmthValue ?? 4) >= 4;
}

// --- Seasons ------------------------------------------------------------
export const SEASONS = ['spring', 'summer', 'fall', 'winter'] as const;
export type Season = (typeof SEASONS)[number];
export type Hemisphere = 'north' | 'south';

const ALL_YEAR = /^(all|all[- ]year|year[- ]round|any|always)$/i;
const SEASON_ALIAS: Record<string, Season> = { autumn: 'fall', spring: 'spring', summer: 'summer', fall: 'fall', winter: 'winter' };

/** The season a month (1–12) falls in, for the given hemisphere. */
export function seasonForMonth(month: number, hemisphere: Hemisphere = 'north'): Season {
  const m = hemisphere === 'south' ? ((month + 5) % 12) + 1 : month;
  if (m === 12 || m <= 2) return 'winter';
  if (m <= 5) return 'spring';
  if (m <= 8) return 'summer';
  return 'fall';
}

export function currentSeason(date: Date = new Date(), hemisphere: Hemisphere = 'north'): Season {
  return seasonForMonth(date.getMonth() + 1, hemisphere);
}

/**
 * Does an item's season list allow wearing it now? An empty list means
 * all-year. `when` is a month (1–12), a date, or { month | date, hemisphere, season }.
 */
export function seasonAllows(
  season: string[] | null | undefined,
  when: number | Date | { month?: number; date?: Date; hemisphere?: Hemisphere; season?: Season } = {},
): boolean {
  if (!season || season.length === 0) return true;
  // The catalogue writes "all" for a year-round piece.
  if (season.some((s) => ALL_YEAR.test(s))) return true;
  let current: Season;
  if (typeof when === 'number') current = seasonForMonth(when);
  else if (when instanceof Date) current = currentSeason(when);
  else if (when.season) current = when.season;
  else if (when.month) current = seasonForMonth(when.month, when.hemisphere);
  else current = currentSeason(when.date ?? new Date(), when.hemisphere);
  const allowed = season.map((s) => SEASON_ALIAS[s.toLowerCase()] ?? s.toLowerCase());
  return allowed.includes(current);
}

// --- Pool hygiene ---------------------------------------------------------
export interface StyleableShape {
  category: string;
  status?: string | null;
  state?: string | null;
  suppressed?: boolean | null;
  owned?: boolean | null;
  twinOfId?: string | null;
  twinResolvedAt?: Date | null;
}

/** A wearable slot: a fabric swatch or a receipt tagged "other" never dresses anyone. */
export function isWearableCategory(category: string | null | undefined): boolean {
  return !!category && category !== 'other';
}

/** A twin flagged on arrival and not yet answered: not two pieces until the person says so. */
export function hasUnresolvedTwin(item: { twinOfId?: string | null; twinResolvedAt?: Date | null }): boolean {
  return item.twinOfId != null && item.twinResolvedAt == null;
}

/**
 * Can this item go into a suggestion pool? Category must be wearable, the
 * catalogue must be done, the piece clean (or in one of `states`), not
 * suppressed, not an unanswered twin, and owned when ownership is known.
 */
export function isStyleable(item: StyleableShape, opts: { states?: readonly string[] } = {}): boolean {
  if (!isWearableCategory(item.category)) return false;
  if (item.status != null && item.status !== 'ready') return false;
  if (item.suppressed) return false;
  if (item.owned === false) return false;
  if (hasUnresolvedTwin(item)) return false;
  const states = opts.states ?? ['clean'];
  if (item.state != null && !states.includes(item.state)) return false;
  return true;
}

// Warmth on a 0–10 TOG-like scale, additive across layers.
// Base value by subtype keyword (first match wins), modified by material.
const WARMTH_BY_KEYWORD: [string, number][] = [
  // Outerwear
  ['parka', 9],
  ['puffer', 8],
  ['down', 8],
  ['overcoat', 7],
  ['coat', 7],
  ['trench', 5],
  ['blazer', 3],
  ['denim jacket', 4],
  ['bomber', 5],
  ['windbreaker', 3],
  ['raincoat', 3],
  ['jacket', 5],
  // Mid layers
  ['fleece', 5],
  ['hoodie', 4],
  ['sweatshirt', 4],
  ['sweater', 5],
  ['jumper', 5],
  ['cardigan', 4],
  ['pullover', 4],
  ['vest', 3],
  // Tops
  ['tank', 0],
  ['camisole', 0],
  ['t-shirt', 1],
  ['tee', 1],
  ['polo', 1],
  ['henley', 2],
  ['flannel', 3],
  ['shirt', 2],
  ['blouse', 1],
  // Bottoms
  ['shorts', 0],
  ['skirt', 1],
  ['linen pant', 1],
  ['chino', 2],
  ['jean', 3],
  ['trouser', 2],
  ['jogger', 3],
  ['legging', 2],
  ['cargo', 3],
  // One-pieces
  ['sundress', 1],
  ['slip dress', 1],
  ['dress', 2],
  ['jumpsuit', 3],
  // Footwear
  ['sandal', 0],
  ['flip', 0],
  ['sneaker', 2],
  ['loafer', 2],
  ['heel', 1],
  ['boot', 4],
  ['oxford', 2],
  ['derby', 2],
];

const CATEGORY_WARMTH_DEFAULT: Record<string, number> = {
  top: 2,
  bottom: 2,
  outerwear: 5,
  footwear: 2,
  dress: 2,
  accessory: 1,
};

const MATERIAL_MODIFIER: [string, number][] = [
  ['wool', 2],
  ['cashmere', 2],
  ['down', 3],
  ['fleece', 1],
  ['shearling', 3],
  ['leather', 1],
  ['corduroy', 1],
  ['linen', -1],
  ['mesh', -1],
  ['silk', -1],
];

export function warmthFor(
  category: string,
  subtype?: string | null,
  material?: string | null,
): number | null {
  const sub = (subtype ?? '').toLowerCase();
  let warmth = WARMTH_BY_KEYWORD.find(([k]) => sub.includes(k))?.[1];
  if (warmth === undefined) warmth = CATEGORY_WARMTH_DEFAULT[category];
  if (warmth === undefined) return null;

  const mat = (material ?? '').toLowerCase();
  const modifier = MATERIAL_MODIFIER.find(([k]) => mat.includes(k))?.[1] ?? 0;
  return Math.max(0, Math.min(10, warmth + modifier));
}

// Controlled color vocabulary, mapped on write. Free-text VLM output produces
// "navy", "dark blue", and "midnight blue" as distinct values, and every
// downstream filter breaks.
const COLOR_CANON: Record<string, string> = {
  'dark blue': 'navy',
  'midnight blue': 'navy',
  'navy blue': 'navy',
  'light blue': 'sky blue',
  'baby blue': 'sky blue',
  'powder blue': 'sky blue',
  'off-white': 'cream',
  'off white': 'cream',
  ivory: 'cream',
  ecru: 'cream',
  eggshell: 'cream',
  'wine red': 'burgundy',
  wine: 'burgundy',
  maroon: 'burgundy',
  'dark red': 'burgundy',
  'light grey': 'grey',
  'light gray': 'grey',
  'dark grey': 'charcoal',
  'dark gray': 'charcoal',
  gray: 'grey',
  'army green': 'olive',
  'olive green': 'olive',
  khaki: 'beige',
  tan: 'beige',
  camel: 'beige',
  sand: 'beige',
  'hot pink': 'pink',
  'light pink': 'pink',
  blush: 'pink',
  'dark green': 'forest green',
  'jet black': 'black',
  'pure white': 'white',
};

export function normalizeColorName(color: string | null | undefined): string | null {
  if (!color) return null;
  const c = color.trim().toLowerCase();
  if (!c) return null;
  return COLOR_CANON[c] ?? c;
}
