// Deterministic reasoning attributes derived from tagged categories.
// Warmth and layer role are looked up, never free-generated by a model:
// consistency across the corpus is what keeps the outfit rules sound.

export type LayerRole = 'base' | 'mid' | 'outer' | 'bottom' | 'footwear' | 'accessory' | 'one-piece';

export const ITEM_STATES = ['clean', 'in-wash', 'packed', 'lent-out', 'retired'] as const;
export type ItemState = (typeof ITEM_STATES)[number];

export const EVENT_TYPES = ['work', 'casual', 'evening', 'occasion', 'athletic'] as const;
export type EventType = (typeof EVENT_TYPES)[number];

// Formality 1–5 target per event type; outfits should sit within ±1.
export const EVENT_FORMALITY: Record<EventType, number> = {
  athletic: 1,
  casual: 2,
  evening: 3,
  work: 4,
  occasion: 5,
};

const FORMALITY_SCORES: Record<string, number> = {
  athletic: 1,
  casual: 2,
  'smart-casual': 3,
  business: 4,
  formal: 5,
};

export function formalityScoreFor(formality: string | null | undefined): number | null {
  if (!formality) return null;
  return FORMALITY_SCORES[formality.toLowerCase()] ?? null;
}

// Subtype keywords that override the category default for layer role.
const MID_LAYER_KEYWORDS = ['sweater', 'jumper', 'cardigan', 'hoodie', 'sweatshirt', 'pullover', 'fleece', 'vest', 'gilet'];

export function layerRoleFor(category: string, subtype?: string | null): LayerRole | null {
  const sub = (subtype ?? '').toLowerCase();
  switch (category) {
    case 'top':
      return MID_LAYER_KEYWORDS.some((k) => sub.includes(k)) ? 'mid' : 'base';
    case 'outerwear':
      return 'outer';
    case 'bottom':
      return 'bottom';
    case 'footwear':
      return 'footwear';
    case 'accessory':
      return 'accessory';
    case 'dress':
      return 'one-piece';
    default:
      return null;
  }
}

// Warmth on a 0–10 TOG-like scale, additive across layers.
// Base value by subtype keyword (first match wins), modified by material.
const WARMTH_BY_KEYWORD: [string, number][] = [
  // Outerwear
  ['parka', 9],
  ['puffer', 8],
  ['down', 8],
  ['overcoat', 7],
  ['coat', 7],
  ['trench', 5],
  ['blazer', 3],
  ['denim jacket', 4],
  ['bomber', 5],
  ['windbreaker', 3],
  ['raincoat', 3],
  ['jacket', 5],
  // Mid layers
  ['fleece', 5],
  ['hoodie', 4],
  ['sweatshirt', 4],
  ['sweater', 5],
  ['jumper', 5],
  ['cardigan', 4],
  ['pullover', 4],
  ['vest', 3],
  // Tops
  ['tank', 0],
  ['camisole', 0],
  ['t-shirt', 1],
  ['tee', 1],
  ['polo', 1],
  ['henley', 2],
  ['flannel', 3],
  ['shirt', 2],
  ['blouse', 1],
  // Bottoms
  ['shorts', 0],
  ['skirt', 1],
  ['linen pant', 1],
  ['chino', 2],
  ['jean', 3],
  ['trouser', 2],
  ['jogger', 3],
  ['legging', 2],
  ['cargo', 3],
  // One-pieces
  ['sundress', 1],
  ['slip dress', 1],
  ['dress', 2],
  ['jumpsuit', 3],
  // Footwear
  ['sandal', 0],
  ['flip', 0],
  ['sneaker', 2],
  ['loafer', 2],
  ['heel', 1],
  ['boot', 4],
  ['oxford', 2],
  ['derby', 2],
];

const CATEGORY_WARMTH_DEFAULT: Record<string, number> = {
  top: 2,
  bottom: 2,
  outerwear: 5,
  footwear: 2,
  dress: 2,
  accessory: 1,
};

const MATERIAL_MODIFIER: [string, number][] = [
  ['wool', 2],
  ['cashmere', 2],
  ['down', 3],
  ['fleece', 1],
  ['shearling', 3],
  ['leather', 1],
  ['corduroy', 1],
  ['linen', -1],
  ['mesh', -1],
  ['silk', -1],
];

export function warmthFor(
  category: string,
  subtype?: string | null,
  material?: string | null,
): number | null {
  const sub = (subtype ?? '').toLowerCase();
  let warmth = WARMTH_BY_KEYWORD.find(([k]) => sub.includes(k))?.[1];
  if (warmth === undefined) warmth = CATEGORY_WARMTH_DEFAULT[category];
  if (warmth === undefined) return null;

  const mat = (material ?? '').toLowerCase();
  const modifier = MATERIAL_MODIFIER.find(([k]) => mat.includes(k))?.[1] ?? 0;
  return Math.max(0, Math.min(10, warmth + modifier));
}

// Controlled color vocabulary, mapped on write. Free-text VLM output produces
// "navy", "dark blue", and "midnight blue" as distinct values, and every
// downstream filter breaks.
const COLOR_CANON: Record<string, string> = {
  'dark blue': 'navy',
  'midnight blue': 'navy',
  'navy blue': 'navy',
  'light blue': 'sky blue',
  'baby blue': 'sky blue',
  'powder blue': 'sky blue',
  'off-white': 'cream',
  'off white': 'cream',
  ivory: 'cream',
  ecru: 'cream',
  eggshell: 'cream',
  'wine red': 'burgundy',
  wine: 'burgundy',
  maroon: 'burgundy',
  'dark red': 'burgundy',
  'light grey': 'grey',
  'light gray': 'grey',
  'dark grey': 'charcoal',
  'dark gray': 'charcoal',
  gray: 'grey',
  'army green': 'olive',
  'olive green': 'olive',
  khaki: 'beige',
  tan: 'beige',
  camel: 'beige',
  sand: 'beige',
  'hot pink': 'pink',
  'light pink': 'pink',
  blush: 'pink',
  'dark green': 'forest green',
  'jet black': 'black',
  'pure white': 'white',
};

export function normalizeColorName(color: string | null | undefined): string | null {
  if (!color) return null;
  const c = color.trim().toLowerCase();
  if (!c) return null;
  return COLOR_CANON[c] ?? c;
}
