// Routes inside the You room. Typed routes are generated by the dev server
// from the files on disk, so while rooms are still being built the generated
// union lags behind; `href()` keeps every push in one place and typed as an
// Href without each call site casting.
import type { Href } from 'expo-router'

export function href(path: string): Href {
  return path as Href
}

export const routes = {
  you: href('/you'),
  journal: (params?: { item?: string; month?: string }) => {
    const q = new URLSearchParams()
    if (params?.item) q.set('item', params.item)
    if (params?.month) q.set('month', params.month)
    const s = q.toString()
    return href(`/you/journal${s ? `?${s}` : ''}`)
  },
  trips: href('/you/trips'),
  newTrip: href('/you/trips/new'),
  trip: (id: string) => href(`/you/trips/${id}`),
  profile: (section?: 'fit' | 'taste' | 'practical' | 'account') => href(`/you/profile${section ? `?section=${section}` : ''}`),
  plan: href('/you/plan'),
  settings: href('/you/settings'),
  notifications: href('/you/notifications'),
  admin: href('/you/admin'),
  mirror: href('/mirror'),
  today: href('/today'),
  closet: href('/closet'),
  // Sheets.
  signOut: href('/sheets/you-sign-out'),
  deleteAccount: href('/sheets/you-delete-account'),
  resale: (itemId: string) => href(`/sheets/you-resale?item=${itemId}`),
  logDay: (date: string) => href(`/sheets/you-log-day?date=${date}`),
  /** The Today room's photo sheet: logs a day from a photo and returns. */
  woreElse: (date: string) => href(`/sheets/today-wore-else?date=${date}`),
  picker: (kind: 'currency') => href(`/sheets/you-picker?kind=${kind}`),
  tripPick: (id: string, index: number, lookId: string, selected: string[]) =>
    href(`/sheets/you-trip-pick?id=${id}&index=${index}&look=${encodeURIComponent(lookId)}&selected=${selected.join(',')}`),
  tripAdd: (id: string) => href(`/sheets/you-trip-add?id=${id}`),
  tripDelete: (id: string) => href(`/sheets/you-trip-delete?id=${id}`),
  adminInvite: (p: { email: string; url: string | null; viaGoogle?: boolean; emailed?: boolean }) => {
    const q = new URLSearchParams({ email: p.email })
    if (p.url) q.set('url', p.url)
    if (p.viaGoogle) q.set('google', '1')
    if (p.emailed) q.set('emailed', '1')
    return href(`/sheets/you-admin-invite?${q.toString()}`)
  },
  adminReset: (id: string, email: string) => href(`/sheets/you-admin-reset?id=${id}&email=${encodeURIComponent(email)}`),
}
