ALTER TABLE "StyleProfile" ADD COLUMN "intents" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "StyleProfile" ADD COLUMN "occasions" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "StyleProfile" ADD COLUMN "fittingStep" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "StyleProfile" ADD COLUMN "fittingCompletedAt" TIMESTAMP(3);
