// Where the Today room goes. Typed routes are generated by the dev server
// from the files on disk, so routes other rooms have not written yet (and
// this room's own, on a fresh checkout) are built here in one place.
import { router, type Href } from 'expo-router'

function q(params: Record<string, string | undefined>): string {
  const s = Object.entries(params)
    .filter((e): e is [string, string] => !!e[1])
    .map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(v)}`)
    .join('&')
  return s ? `?${s}` : ''
}

export const paths = {
  day: (date: string, opts: { laidOut?: boolean } = {}) => `/(tabs)/today/day/${date}${q({ laidOut: opts.laidOut ? '1' : undefined })}`,
  mirror: (itemIds: string[]) => `/(tabs)/mirror?items=${encodeURIComponent(itemIds.join(','))}`,
  closet: '/(tabs)/closet',
  basket: '/(tabs)/closet/basket',
  wishlist: '/(tabs)/closet/wishlist',
  compose: '/(tabs)/closet/compose',
  circle: '/(tabs)/circle',
  profile: '/(tabs)/you/profile',
  person: (handle: string) => `/u/${encodeURIComponent(handle)}`,
  trip: (id: string) => `/(tabs)/you/trips/${id}`,
  // this room's sheets
  addLook: (date: string) => `/sheets/today-add-look${q({ date })}`,
  reconsider: (date: string, itemId: string) => `/sheets/today-reconsider${q({ date, itemId })}`,
  woreElse: (p: { date: string; eventType?: string | null; alreadyLogged?: boolean; hasSuggestion?: boolean }) =>
    `/sheets/today-wore-else${q({ date: p.date, eventType: p.eventType ?? undefined, alreadyLogged: p.alreadyLogged ? '1' : undefined, hasSuggestion: p.hasSuggestion ? '1' : undefined })}`,
  share: (p: { date: string; wearLogId?: string | null; lookId?: string | null }) =>
    `/sheets/today-share${q({ date: p.date, wearLogId: p.wearLogId ?? undefined, lookId: p.lookId ?? undefined })}`,
}

export function go(path: string) {
  router.push(path as Href)
}

export function replaceWith(path: string) {
  router.replace(path as Href)
}
